site:
  title: 'EverPay'
  baseline: "Open Payments"
  baseurl: 'https://optimistic-goodall-4d2b12.netlify.com'
  canonicalurl: true
  description: "Everpay provides merchant account and payment solutions for businesses worldwide."
  paginate:
    max: 5
    path: 'page'
  date:
    format: 'j F Y'
    timezone: 'Europe/Paris'
  netlify:
    cms:
      path: 'admin'
      version: 'latest'
    identity:
      version: 'v1'
  fmpages:
    admin:
      layout: admin/index.html
      title: 'Content Manager (Netlify CMS)'
    redirects:
      layout: _redirects.txt
      permalink: _redirects
theme: 'hyde'
