[build]
  command = "chmod +x netlify.sh && bash netlify.sh"
  publish = "_site"
  environment = { PHP_VERSION = "7.2" }

[context.deploy-preview]
  command = "chmod +x netlify.sh && bash netlify.sh $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "chmod +x netlify.sh && bash netlify.sh $DEPLOY_PRIME_URL"

[template.environment]
  CECIL_SITE_TITLE = "Everpay"
  CECIL_SITE_BASELINE = "Short description (~ 20 characters)"
  CECIL_SITE_DESCRIPTION = "Full description(~ 250 characters)"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    # COMMENT: Multi-key header rules are expressed with multi-line strings
